verb_set = [
    ["see","saw","seen","seeing","sees"],
    ["hear","heard","hearing","hears"],
    ["listen","listened","listening","listens"],
    ["taste","tasted","tasting","tastes"],
    ["smell","smelled","smelling","smells"],
    ["eat","ate","eating","eats"],
    ["touch","touched","touching","touches"],
    ["rub","rubbed","rubbing","rubs"],
    ["lift","lifted","lifting","lifts"],
    # ["manipulate","manipulated","manipulating","manipulates"],
    ["run","ran","running","runs"],
    ["push","pushed","pushing","pushes"],
    ["fill","filled","filling","fills"],
    ["move","moved","moving","moves"],
    ["ride","rode","riding","rides"],
    ["say","said","saying","says"],
    ["fear","feared","fearing","fears"],
    ["open","opened","opening","opens"],
    ["approach","approached","approaching","approaches"],
    ["near","neared","nearing","nears"],
    ["enter","entered","entering","enters"],
    ["drive","drove","driving","drives","driven"],
    ["wear","wore","wearing","wears"],
    ["break","broke","breaking","breaks"],
    ["clean","cleaned","cleaning","cleans"], ## Up through here is the Mitchell/Just set ##
    
    ["accept","accepted","accepting","accepts"],
    ["account","accounted","accounting","accounts"],
    ["achieve","achieved","achieving","achieves"],
    ["act","acted","acting","acts"],
    ["add","added","adding","adds"],
    ["admit","admitted","admitting","admits"],
    ["affect","affected","affecting","affects"],
    ["afford","afforded","affording","affords"],
    ["agree","agreed","agreeing","agrees"],
    ["aim","aimed","aiming","aims"],
    ["allow","allowed","allowing","allows"],
    ["answer","answered","answering","answers"],
    ["appear","appeared","appearing","appears"],
    ["apply","applied","applying","applies"],
    ["argue","argued","arguing","argued"],
    ["arrange","arranged","arranging","arranged"],
    ["arrive","arrived","arriving","arrived"],
    ["ask","asked","asking","asks"],
    ["attack","attacked","attacking","attacks"],
    ["avoid","avoided","avoiding","avoids"],
    
    ["base","based","basing","bases"],
    ["beat","beating","beats"],
    ["become","became","becoming","becomes"],
    ["begin","began","beginning","begins"],
    ["believe","believed","believing","believes"],
    ["belong","belonged","belonging","belongs"],
    ["build","built","building","builds"],
    ["burn","burned","burning","burns"],
    ["buy","bought","buying","buys"],
    
    ["call","called","calling","calls"],
    ["care","cared","caring","cares"],
    ["carry","carried","carrying","carries"],
    ["catch","caught","catching","catches"],
    ["cause","caused","causing","causes"],
    ["change","changed","changing","changes"],
    ["choose","chose","choosing","chooses"],
    ["claim","claimed","claiming","claims"],
    ["clear","cleared","clearing","clears"],
    ["climb","climbed","climbing","climbs"],
    ["close","closed","closing","closes"],
    ["collect","collected","collecting","collects"],
    ["commit","committed","committing","commits"],
    ["compare","compared","comparing","compares"],
    ["complain","complained","complaining","complains"],
    ["complete","completed","completing","completes"],
    ["concern","concerned","concerning","concerns"],
    ["confirm","confirmed","confirming","confirms"],
    ["connect","connected","connecting","connects"],
    ["consider","considered","considering","considers"],
    ["consist","consisted","consisting","consists"],
    ["contact","contacted","contacting","contacts"],
    ["contain","contained","containing","contains"],
    ["continue","continued","continuing","continues"],
    # ["contribute","contributed","contributing","contributes"],
    ["control","controlled","controlling","controls"],
    ["cook","cooked","cooking","cooks"],
    ["copy","copied","copying","copies"],
    ["correct","corrected","correcting","corrects"],
    ["cost","costing","costs"],
    ["count","counted","counting","counts"],
    ["cover","covered","covering","covers"],
    ["create","created","creating","creates"],
    ["cross","crossed","crossing","crosses"],
    ["cry","cried","crying","cries"],
    ["cut","cutting","cuts"],
    
    ["damage","damaged","damaging","damages"],
    ["dance","danced","dancing","dances"],
    ["deal","dealt","dealing","deals"],
    ["decide","decided","deciding","decides"],
    ["deliver","delivered","delivering","delivers"],
    ["demand","demanded","demanding","demands"],
    ["deny","denied","denying","denies"],
    ["depend","depended","depending","depends"],
    ["describe","described","describing","describes"],
    ["design","designed","designing","designed"],
    ["destroy","destroyed","destroying","destroys"],
    ["develop","developed","developing","develops"],
    ["die","died","dying","dies"],
    ["disappear","disappeared","disappearing","disappears"],
    ["discover","discovered","discovering","discovers"],
    ["discuss","discussed","discussing","discusses"],
    ["divide","divided","dividing","divides"],
    ["draw","drew","drawing","draws"],
    ["dress","dressed","dressing","dresses"],
    ["drink","drank","drinking","drinks"],
    ["drop","dropped","dropping","drops"],
    
    ["enable","enabled","enabling","enables"],
    ["encourage","encouraged","encouraging","encourages"],
    ["end","ended","ending","ends"],
    ["enjoy","enjoyed","enjoying","enjoys"],
    ["examine","examined","examining","examines"],
    ["exist","existed","existing","exists"],
    ["expect","expected","expecting","expects"],
    ["experience","experienced","experiencing","experiences"],
    ["explain","explained","explaining","explains"],
    ["express","expressed","expressing","expresses"],
    ["extend","extended","extending","extends"],
    
    ["face","faced","facing","faces"],
    ["fail","failed","failing","fails"],
    ["fall","fell","falling","falls"],
    ["fasten","fastened","fastening","fastened"],
    ["feed","fed","feeding","feeds"],
    ["feel","felt","feeling","feels"],
    ["fight","fought","fighting","fights"],
    ["find","found","finding","finds"],
    ["finish","finished","finishing","finishes"],
    ["fit","fitting","fits"],
    ["fly","flew","flying","flies"],
    ["fold","folded","folding","folds"],
    ["follow","followed","following","follows"],
    ["force","forced","forcing","forces"],
    ["forget","forgot","forgetting","forgets"],
    ["forgive","forgave","forgiving","forgives"],
    ["form","formed","forming","forms"],
    ["found","founded","founding","founds"],
    
    ["gain","gained","gaining","gains"],
    ["get","got","getting","gets"],
    ["give","gave","giving","gives"],
    ["grow","grew","growing","grows"],
    
    ["handle","handled","handling","handles"],
    ["happen","happened","happening","happens"],
    ["hate","hated","hating","hates"],
    ["head","headed","heading","heads"],
    ["help","helped","helping","helps"],
    ["hide","hid","hiding","hides"],
    ["hit","hitting","hits"],
    ["hold","held","holding","holds"],
    ["hope","hoped","hoping","hopes"],
    ["hurt","hurting","hurts"],
    
    ["identify","identified","identifying","identifies"],
    ["imagine","imagined","imagining","imagines"],
    ["improve","improved","improving","improves"],
    ["include","included","including","includes"],
    ["increase","increased","increasing","increases"],
    ["indicate","indicated","indicating","indicates"],
    ["influence","influenced","influencing","influences"],
    ["inform","informed","informing","informs"],
    ["intend","intended","intending","intends"],
    ["introduce","introduced","introducing","introduces"],
    ["invite","invited","inviting","invites"],
    ["involve","involved","involving","involves"],
    
    ["join","joined","joining","joins"],
    ["jump","jumped","jumping","jumps"],
    
    ["keep","kept","keeping","keeps"],
    ["kick","kicked","kicking","kicks"],
    ["kill","killed","killing","kills"],
    ["knock","knocked","knocking","knocks"],
    ["know","knew","knowing","knows"],
    
    ["last","lasted","lasting","lasts"],
    ["laugh","laughed","laughing","laughs"],
    ["lay","laid","laying","lays"],
    ["lead","leading","leads"],
    ["learn","learned","learning","learns"],
    ["leave","left","leaving","leaves"],
    ["lend","lent","lending","lends"],
    ["let","letting","lets"],
    ["lie","lied","lying","lies"],
    ["like","liked","liking","likes"],
    ["limit","limited","limiting","limits"],
    ["link","linked","linking","links"],
    ["live","lived","living","lives"],
    ["look","looked","looking","looks"],
    ["lose","lost","losing","loses"],
    ["love","loved","loving","loves"],
    
    ["make","made","making","makes"],
    ["manage","managed","managing","manages"],
    ["mark","marked","marking","marks"],
    ["matter","mattered","mattering","matters"],
    ["mean","meant","meaning","means"],
    ["measure","measured","measuring","measures"],
    ["meet","met","meeting","meets"],
    ["mention","mentioned","mentioning","mentions"],
    ["mind","minded","minding","minds"],
    ["miss","missed","missing","misses"],
    
    ["need","needed","needing","needs"],
    ["notice","noticed","noticing","noticed"],
    
    ["obtain","obtained","obtaining","obtains"],
    ["occur","occurred","occurring","occurs"],
    ["offer","offered","offering","offers"],
    ["order","ordered","ordering","orders"],
    ["own","owned","owning","owns"],
    
    ["pass","passed","passing","passes"],
    ["pay","paid","paying","pays"],
    ["perform","performed","performing","performed"],
    ["pick","picked","picking","picks"],
    ["place","placed","placing","places"],
    ["plan","planned","planning","plans"],
    ["play","played","playing","plays"],
    ["point","pointed","pointing","points"],
    ["prefer","preferred","preferring","prefers"],
    ["prepare","prepared","preparing","prepares"],
    ["present","presented","presenting","presents"],
    ["press","pressed","pressing","presses"],
    ["prevent","prevented","preventing","prevents"],
    ["produce","produced","producing","produces"],
    ["promise","promised","promising","promises"],
    ["protect","protected","protecting","protects"],
    ["prove","proved","proving","proves"],
    ["provide","provided","providing","provides"],
    ["publish","published","publishing","publishes"],
    ["pull","pulled","pulling","pulls"],
    ["put","putting","puts"],
    
    ["raise","raised","raising","raised"],
    ["reach","reached","reaching","reaches"],
    ["read","reading","reads"],
    ["realize","realized","realizing","realizes"],
    ["receive","received","receiving","receives"],
    ["recognize","recognized","recognizing","recognizes"],
    ["record","recorded","recording","records"],
    ["reduce","reduced","reducing","reduces"],
    ["refer","referred","referring","refers"],
    ["reflect","reflected","reflecting","reflects"],
    ["refuse","refused","refusing","refuses"],
    ["regard","regarded","regarding","regards"],
    ["relate","related","relating","relates"],
    ["release","released","releasing","releases"],
    ["remain","remained","remaining","remains"],
    ["remember","remembered","remembering","remembers"],
    ["remove","removed","removing","removes"],
    ["repeat","repeated","repeating","repeats"],
    ["replace","replaced","replacing","replaces"],
    ["reply","replied","replying","replies"],
    ["report","reported","reporting","reports"],
    ["represent","represented","representing","represents"],
    ["require","required","requiring","requires"],
    ["rest","rested","resting","rests"],
    ["result","resulted","resulting","results"],
    ["return","returned","returning","returns"],
    ["reveal","revealed","revealing","reveals"],
    ["ring","rang","ringing","rings"],
    ["rise","rose","rising","rises"],
    ["roll","rolled","rolling","rolls"],
    
    ["save","saved","saving","saves"],
    ["seem","seemed","seeming","seems"],
    ["sell","sold","selling","sells"],
    ["send","sent","sending","sends"],
    ["separate","separated","separating","separates"],
    ["serve","served","serving","serves"],
    ["set","setting","sets"],
    ["settle","settled","settling","settles"],
    ["shake","shook","shaking","shakes"],
    ["share","shared","sharing","shares"],
    ["shoot","shot","shooting","shoots"],
    ["shout","shouted","shouting","shouts"],
    ["show","showed","showing","shows"],
    ["shut","shutting","shuts"],
    ["sing","sang","singing","sings"],
    ["sit","sat","sitting","sits"],
    ["sleep","slept","sleeping","sleeps"],
    ["smile","smiled","smiling","smiles"],
    ["sort","sorted","sorting","sorts"],
    ["sound","sounded","sounding","sounds"],
    ["speak","spoke","speaking","speaks"],
    ["stand","stood","standing","stands"],
    ["start","started","starting","starts"],
    ["state","stated","stating","states"],
    ["stay","stayed","staying","stays"],
    ["stick","stuck","sticking","sticks"],
    ["stop","stopped","stopping","stops"],
    ["study","studied","studying","studies"],
    ["succeed","succeeded","succeeding","succeeds"],
    ["suffer","suffered","suffering","suffers"],
    ["suggest","suggested","suggesting","suggests"],
    ["suit","suited","suiting","suits"],
    ["supply","supplied","supplying","supplies"],
    ["support","supported","supporting","supports"],
    ["supposed","supposing","supposes"],
    ["survive","survived","surviving","survives"],
    
    ["take","took","taking","takes"],
    ["talk","talked","talking","talks"],
    ["teach","taught","teaching","teaches"],
    ["tell","told","telling","tells"],
    ["tend","tended","tending","tends"],
    ["test","tested","testing","tests"],
    ["thank","thanked","thanking","thanks"],
    ["think","thought","thinking","thinks"],
    ["throw","threw","throwing","throws"],
    ["train","trained","training","trains"],
    ["travel","traveled","traveling","travels"],
    ["treat","treated","treating","treats"],
    ["try","tried","trying","tries"],
    ["turn","turned","turning","turns"],
    
    ["understand","understood","understanding","understands"],
    ["use","used","using","uses"],
    
    ["visit","visited","visiting","visits"],
    ["vote","voted","voting","votes"],
    
    ["wait","waited","waiting","waits"],
    ["walk","walked","walking","walks"],
    ["want","wanted","wanting","wants"],
    ["warn","warned","warning","warns"],
    ["wash","washed","washing","washes"],
    ["watch","watched","watching","watches"],
    ["win","won","winning","wins"],
    ["wish","wishes","wishing","wishes"],
    ["wonder","wondered","wondering","wonders"],
    ["work","worked","working","works"],
    ["worry","worried","worrying","worries"],
    ["write","wrote","writing","writes"]]

preposition_set = [
    "aboard", "about", "above", "across", "after", "against", "along", "alongside", "amid", "amidst", "among", "amongst", "around", "as", "aside", "astride", "at", "athwart", "atop",
    "barring", "before", "behind", "below", "beneath", "beside", "besides", "between", "beyond", "but", "by",
    "circa", "concerning",
    "despite", "down", "during",
    "except",
    "failing", "following", "for", "from",
    "given",
    "in", "inside", "into",
    "like",
    "minus",
    "near", "next", "notwithstanding",
    "of", "off", "on", "onto", "opposite", "out", "outside", "over",
    "pace", "past", "per", "plus",
    "regarding", "round",
    "save", "since",
    "than", "through", "throughout", "till", "times", "to", "toward", "towards",
    "under", "underneath", "unlike", "until", "up", "upon",
    "versus", "via",
    "with", "within", "without", "worth"]

adjective_set = [
    "aback", "abaft", "abandoned", "abashed", "aberrant", "abhorrent", "abiding", "abject", "ablaze", "abnormal", "aboard", "aboriginal", "abortive", "abounding", "abrasive", "abrupt", "absent", "absorbed", "absorbing", "abstracted", "absurd", "abusive", "acceptable", "accessible", "accidental", "accurate", "acoustic", "acrid", "actually", "ad", "hoc", "adamant", "adaptable", "addicted", "adhesive", "adjoining", "adorable", "afraid", "agonizing", "ahead", "alcoholic", "alert", "alike", "alive", "alleged", "alluring", "aloof", "ambiguous", "ambitious", "amuck", "ancient", "animated", "apathetic", "aquatic", "aromatic", "aspiring", "assorted", "astonishing", "auspicious", "available", "average", "aware", "axiomatic",
    "bad", "barbarous", "bashful", "bawdy", "beautiful", "befitting", "belligerent", "berserk", "better", "big", "billowy", "bizarre", "black", "boiling", "boorish", "boring", "boundless", "brash", "brawny", "breezy", "brief", "bright", "broad", "broken", "bumpy", "burly",
    "cagey", "callous", "capable", "capricious", "ceaseless", "changeable", "cheerful", "childlike", "chilly", "chivalrous", "chubby", "chunky", "clammy", "classy", "cloistered", "cloudy", "clumsy", "coherent", "cold", "colossal", "combative", "comfortable", "cooing", "cool", "cooperative", "courageous", "cowardly", "crabby", "craven", "crazy", "credible", "creepy", "crooked", "cuddly", "cultured", "curly", "curved", "cynical", 
    "daffy", "daily", "damaged", "damaging", "damp", "dapper", "dashing", "dazzling", "deadpan", "debonair", "decisive", "decorous", "deep", "deeply", "defective", "delightful", "demonic", "deranged", "deserted", "detailed", "determined", "devilish", "didactic", "diligent", "direful", "dirty", "disagreeable", "discreet", "disillusioned", "dispensable", "divergent", "dizzy", "domineering", "draconian", "dramatic", "drunk", "dry", "dull", "dusty", "dynamic", "dysfunctional", 
    "eager", "early", "earsplitting", "earthy", "eatable", "economic", "educated", "efficacious", "efficient", "elated", "elderly", "elfin", "elite", "eminent", "empty", "enchanting", "encouraging", "endurable", "energetic", "entertaining", "enthusiastic", "equable", "erect", "erratic", "ethereal", "evanescent", "evasive", "evil", "excellent", "excited", "exclusive", "exotic", "expensive", "exuberant", "exultant", 
    "fabulous", "faded", "fallacious", "fanatical", "fancy", "fantastic", "fascinated", "fast", "fat", "faulty", "fearless", "feigned", "fertile", "festive", "filthy", "finicky", "flagrant", "flashy", "flawless", "flippant", "flowery", "foamy", "foregoing", "forgetful", "fortunate", "frail", "fretful", "friendly", "functional", "funny", "furtive", "futuristic", 
    "gabby", "gainful", "gamy", "gaping", "garrulous", "gaudy", "gentle", "giant", "giddy", "gigantic", "glamorous", "gleaming", "glib", "glorious", "glossy", "godly", "good", "goofy", "gorgeous", "graceful", "grandiose", "gratis", "great", "greedy", "green", "groovy", "grotesque", "grouchy", "gruesome", "grumpy", "guarded", "guiltless", "gullible", "gusty", "guttural", 
    "habitual", "half", "hallowed", "halting", "handsome", "handsomely", "hapless", "happy", "harmonious", "heady", "healthy", "heartbreaking", "heavenly", "heavy", "hellish", "helpful", "hesitant", "high", "highfalutin", "hilarious", "historical", "holistic", "hollow", "honorable", "horrible", "hospitable", "huge", "hulking", "humdrum", "humorous", "hungry", "hurried", "hurt", "hypnotic", "hysterical", 
    "icky", "idiotic", "ignorant", "illegal", "illustrious", "imaginary", "immense", "imminent", "impartial", "imperfect", "imported", "incandescent", "incompetent", "inconclusive", "industrious", "innate", "instinctive", "internal", "invincible", "irate", "itchy", 
    "jaded", "jagged", "jazzy", "jealous", "jittery", "jobless", "jolly", "joyous", "judicious", "jumbled", "jumpy", "juvenile", 
    "kaput", "kind", "kindhearted", "knotty", "knowing", "knowledgeable", "known", 
    "labored", "lackadaisical", "lacking", "lamentable", "languid", "large", "late", "laughable", "lavish", "lazy", "lean", "learned", "legal", "lethal", "level", "lewd", "light", "likeable", "literate", "little", "lively", "long", "longing", "lopsided", "loutish", "lovely", "loving", "low", "lowly", "lucky", "ludicrous", "lush", "luxuriant", "lying", "lyrical", 
    "macabre", "macho", "maddening", "madly", "magenta", "magical", "magnificent", "majestic", "makeshift", "malicious", "mammoth", "maniacal", "many", "marked", "massive", "materialistic", "mature", "measly", "meek", "melodic", "merciful", "mere", "mighty", "mindless", "miniature", "minor", "miscreant", "moaning", "modern", "moldy", "momentous", "muddled", "mundane", "murky", "mushy", "mysterious", 
    "naive", "nappy", "narrow", "nasty", "nauseating", "nebulous", "needless", "needy", "neighborly", "nervous", "new", "nice", "nifty", "noiseless", "noisy", "nonchalant", "nondescript", "nonstop", "nostalgic", "nosy", "noxious", "null", "numberless", "numerous", "nutritious", 
    "oafish", "obedient", "obeisant", "obscene", "obsequious", "observant", "obsolete", "obtainable", "oceanic", "odd", "offbeat", "old", "omniscient", "onerous", "optimal", "orange", "ordinary", "organic", "ossified", "oval", "overconfident", "overjoyed", "overrated", "overt", "overwrought", 
    "painful", "painstaking", "panoramic", "parched", "parsimonious", "pastoral", "pathetic", "peaceful", "penitent", "perfect", "periodic", "permissible", "perpetual", "petite", "phobic", "picayune", "piquant", "placid", "plant", "plant", "plausible", "pleasant", "plucky", "pointless", "political", "possessive", "precious", "premium", "pretty", "prickly", "productive", "profuse", "protective", "proud", "psychedelic", "psychotic", "puffy", "pumped", "puny", "purple", 
    "quack", "quaint", "quarrelsome", "questionable", "quick", "quickest", "quiet", "quixotic", "quizzical", 
    "rabid", "racial", "ragged", "rainy", "rambunctious", "rampant", "rare", "raspy", "ratty", "rebel", "receptive", "recondite", "red", "redundant", "reflective", "relieved", "reminiscent", "resolute", "resonant", "rhetorical", "righteous", "rightful", "ritzy", "roasted", "robust", "romantic", "roomy", "round", "royal", "ruddy", "rural", "rustic", "ruthless", 
    "sable", "sad", "sassy", "satisfying", "savoy", "scandalous", "scarce", "scary", "scientific", "scintillating", "scrawny", "secretive", "sedate", "seemly", "selective", "shallow", "shocking", "short", "shrill", "silly", "sincere", "skillful", "skinny", "sloppy", "slow", "small", "smelly", "sneaky", "snobbish", "snotty", "soggy", "somber", "sordid", "spectacular", "spicy", "spiffy", "spiritual", "splendid", "spooky", "spurious", "squalid", "square", "squeamish", "staking", "standing", "statuesque", "steadfast", "stereotyped", "stimulating", "stingy", "strange", "subdued", "subsequent", "successful", "succinct", "sulky", "supreme", "swanky", "sweltering", "symptomatic", "synonymous", 
    "taboo", "tacit", "tacky", "talented", "tall", "tame", "tan", "tangible", "tangy", "tart", "tasteful", "tawdry", "tearful", "telling", "temporary", "tender", "tenuous", "tested", "testy", "therapeutic", "thinkable", "threatening", "tight", "tightfisted", "tiny", "tiresome", "toothsome", "torpid", "tough", "towering", "tranquil", "trashy", "tricky", "trite", "truculent", "typical", 
    "ubiquitous", "ugliest", "ugly", "ultra", "unable", "unaccountable", "unadvised", "unarmed", "unbecoming", "unbiased", "uncovered", "understood", "undesirable", "unequaled", "uneven", "unsightly", "unsuitable", "unusual", "upbeat", "uppity", "upset", "uptight", "used", "utopian", "utter", "uttermost", 
    "vacuous", "vagabond", "vague", "various", "vast", "vengeful", "venomous", "verdant", "versed", "victorious", "vigorous", "vivacious", "voiceless", "volatile", "voracious", "vulgar", 
    "wacky", "waggish", "wakeful", "wanting", "warlike", "warm", "wary", "wasteful", "wasteful", "watchful", "watery", "weak", "wealthy", "weary", "wee", "wet", "whimsical", "whispering", "wholesale", "wicked", "wide", "willing", "wiry", "wise", "wistful", "woebegone", "womanly", "wonderful", "wooden", "woozy", "workable", "worried", "worthless", "wrathful", "wretched", "wry", 
    "x-rated", 
    "yellow", "yielding", "young", "youthful", "yummy", 
    "zany", "zealous", "zippy", "zonked"]

adjective_set2 = ["big large fat huge gigantic",
                  "little small thin skinny tiny",
                  "fast quick speedy brisk swift",
                  "slow idle sluggish",
                  "old ancient",]

noun_set = [
    "crowd", "people", "gathering",
    "person", "body", "man", "woman", "baby", "child",
    "arm", "leg", "torso", "hand", "foot"
    "portrait", "head", "face",
    "animal", "horse", "cow", "mammal", "dog", "cat",
    "whale", "dolphin",
    "bird", "parrot", "hawk", "finch",
    "fish", "cod", "halibut", "salmon",
    "insect", "bug", "ant", "fly", "bee",
    "vehicle", "car", "van", "bus", "bike",
    "artifact",
    "indoors", 
    "outdoors", 
    "fruit", "apple", "grape", "peach",
    "vegetable", "tomato", "cucumber", "lettuce", "leek",
    "tree", "forest", "grove", "sapling",
    "bush", "vine",
    "land", "ground", "dirt", "pavement",
    "ocean", "sea", "lake", "water",
    "sky", "clouds",
    "bark", "leaves",
    "text", "words", "writing",
    "metal", "concrete"]

english1000 = [[w] for w in sorted(set([w.lower() for w in """a, about, above, across, act, active, activity, add, afraid, after, again, age, ago, agree, air, all, alone, along, already, always, am, amount, an, and, angry, another, answer, any, anyone, anything, appear, apple, are, area, arm, army, around, arrive, art, as, ask, at, attack, aunt, autumn, away, baby, base, back, bad, bag, ball, bank, basket, bath, be, bear, beautiful, beer, bed, bedroom, behave, before, begin, behind, bell, below, besides, best, better, between, big, bird, birth, birthday, bit, bite, black, block, blood, blow, blue, board, boat, body, boil, bone, book, border, born, borrow, both, bottle, bottom, bowl, box, boy, branch, brave, bread, break, breakfast, breathe, bridge, bright, bring, brother, brown, brush, build, burn, business, bus, busy, but, buy, by, cake, call, can, candle, cap, car, card, care, careful, careless, carry, case, cat, catch, central, century, certain, chair, chance, change, chase, cheap, cheese, chicken, child, children, chocolate, choice, choose, circle, city, class, clever, clean, clear, climb, clock, cloth, clothes, cloud, cloudy, close, coffee, coat, coin, cold, collect, colour, comb, comfortable, common, compare, come, complete, computer, condition, continue, control, cook, cool, copper, corn, corner, correct, cost, contain, count, country, course, cover, crash, cross, cry, cup, cupboard, cut, dance, dangerous, dark, daughter, day, dead, decide, deep, deer, depend, desk, destroy, develop, die, different, difficult, dinner, direction, dirty, discover, dish, do, dog, door, double, down, draw, dream, dress, drink, drive, drop, dry, duck, dust, duty, each, ear, early, earn, earth, east, easy, eat, education, effect, egg, eight, either, electric, elephant, else, empty, end, enemy, enjoy, enough, enter, equal, entrance, escape, even, evening, event, ever, every, everyone, exact, everybody, examination, example, except, excited, exercise, expect, expensive, explain, extremely, eye, face, fact, fail, fall, false, family, famous, far, farm, father, fast, fat, fault, fear, feed, feel, female, fever, few, fight, fill, film, find, fine, finger, finish, fire, first, fit, five, fix, flag, flat, float, floor, flower, fly, fold, food, fool, foot, football, for, force, foreign, forest, forget, forgive, fork, form, fox, four, free, freedom, freeze, fresh, friend, friendly, from, front, fruit, full, fun, funny, furniture, further, future, game, garden, gate, general, gentleman, get, gift, give, glad, glass, go, goat, god, gold, good, goodbye, grandfather, grandmother, grass, grave, great, green, grey, ground, group, grow, gun, hair, half, hall, hammer, hand, happen, happy, hard, hat, hate, have, he, head, healthy, hear, heavy, hello, help, heart, heaven, height, help, her, here, hers, hide, high, hill, him, his, hit, hobby, hold, hole, holiday, home, hope, horse, hospital, hot, hotel, house, how, hundred, hungry, hour, hurry, husband, hurt, I, ice, idea, if, important, in, increase, inside, into, introduce, iron, invite, is, island, it, its, jelly, job, join, juice, jump, just, keep, key, kill, kind, king, kitchen, knee, knife, knock, know, ladder, lady, lamp, land, large, last, late, lately, laugh, lazy, lead, leaf, learn, leave, leg, left, lend, length, less, lesson, let, letter, library, lie, life, light, like, lion, lip, list, listen, little, live, lock, lonely, long, look, lose, lot, love, low, lower, luck, machine, main, make, male, man, many, map, mark, market, marry, matter, may, me, meal, mean, measure, meat, medicine, meet, member, mention, method, middle, milk, million, mind, minute, miss, mistake, mix, model, modern, moment, money, monkey, month, moon, more, morning, most, mother, mountain, mouth, move, much, music, must, my, name, narrow, nation, nature, near, nearly, neck, need, needle, neighbour, neither, net, never, new, news, newspaper, next, nice, night, nine, no, noble, noise, none, nor, north, nose, not, nothing, notice, now, number, obey, object, ocean, of, off, offer, office, often, oil, old, on, one, only, open, opposite, or, orange, order, other, our, out, outside, over, own, page, pain, paint, pair, pan, paper, parent, park, part, partner, party, pass, past, path, pay, peace, pen, pencil, people, per, perfect, period, person, photograph, piano, pick, picture, piece, pig, pin, pink, place, plane, plant, plastic, plate, play, please, pleased, plenty, pocket, point, poison, police, polite, pool, poor, popular, position, possible, potato, pour, power, present, press, pretty, prevent, price, prince, prison, private, prize, probably, problem, produce, promise, proper, protect, provide, public, pull, punish, pupil, push, put, queen, question, quick, quiet, quite, radio, rain, raise, reach, read, ready, real, really, receive, record, red, remember, remind, remove, rent, repair, repeat, reply, report, rest, restaurant, result, return, rice, rich, ride, right, ring, rise, road, rob, rock, room, round, rubber, rude, rule, ruler, run, rush, sad, safe, sail, salt, same, sand, save, say, school, science, search, seat, second, see, seem, sell, send, sentence, serve, seven, several, sex, shade, shadow, shake, shape, share, sharp, she, sheep, sheet, shelf, shine, ship, shirt, shoe, shoot, shop, short, should, shoulder, shout, show, sick, side, signal, silence, silly, silver, similar, simple, single, since, sing, sink, sister, sit, six, size, skill, skin, skirt, sky, sleep, slip, slow, smoke, small, smell, smile, smoke, snow, so, soap, sock, soft, some, someone, something, sometimes, son, soon, sorry, sound, soup, south, space, speak, special, speed, spell, spend, spoon, sport, spread, spring, square, stamp, stand, star, start, station, stay, steal, steam, step, still, stomach, stone, stop, store, storm, story, strange, street, strong, structure, student, study, stupid, subject, substance, successful, such, sudden, sugar, suitable, summer, sun, sunny, support, sure, surprise, sweet, swim, sword, table, take, talk, tall, taste, taxi, tea, teach, team, tear, telephone, television, tell, ten, tennis, terrible, test, than, that, the, their, then, there, therefore, these, thick, thin, thing, think, third, this, though, threat, three, tidy, tie, title, to, today, toe, together, tomorrow, tonight, too, tool, tooth, top, total, touch, town, train, travel, tree, trouble, true, trust, two, twice, try, turn, type, uncle, under, understand, unit, until, up, use, useful, usual, usually, vegetable, very, village, voice, visit, wait, wake, walk, want, warm, wash, waste, watch, water, way, we, weak, wear, weather, wedding, week, weight, welcome, well, west, wet, what, wheel, when, where, which, while, white, who, why, wide, wife, wild, will, win, wind, window, wine, winter, wire, wise, wish, with, without, woman, wonder, word, work, world, worry, worst, write, wrong, year, yes, yesterday, yet, you, young, your, zero""".split(", ")]))]
